-- MySQL Script generated by MySQL Workbench
-- Mon Feb 24 08:20:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestorDatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gestorDatabase` ;

-- -----------------------------------------------------
-- Schema gestorDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestorDatabase` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `gestorDatabase` ;

-- -----------------------------------------------------
-- Table `gestorDatabase`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorDatabase`.`students` (
  `studentId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`studentId`),
  UNIQUE INDEX `userId_UNIQUE` (`studentId` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `gestorDatabase`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorDatabase`.`teachers` (
  `teacherId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`teacherId`),
  UNIQUE INDEX `teacherId_UNIQUE` (`teacherId` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf32;


-- -----------------------------------------------------
-- Table `gestorDatabase`.`parents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorDatabase`.`parents` (
  `parentId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`parentId`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `parentId_UNIQUE` (`parentId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `gestorDatabase`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorDatabase`.`subjects` (
  `subjectId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subjectId`),
  UNIQUE INDEX `subjectId_UNIQUE` (`subjectId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `gestorDatabase`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorDatabase`.`grades` (
  `gradeId` INT NOT NULL AUTO_INCREMENT,
  `value` DECIMAL(2,1) NOT NULL,
  `students_studentId` INT NOT NULL,
  `subjects_subjectId` INT NOT NULL,
  PRIMARY KEY (`gradeId`),
  INDEX `fk_grades_students1_idx` (`students_studentId` ASC) VISIBLE,
  UNIQUE INDEX `gradeId_UNIQUE` (`gradeId` ASC) VISIBLE,
  INDEX `fk_grades_subjects1_idx` (`subjects_subjectId` ASC) VISIBLE,
  CONSTRAINT `fk_grades_students1`
    FOREIGN KEY (`students_studentId`)
    REFERENCES `gestorDatabase`.`students` (`studentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grades_subjects1`
    FOREIGN KEY (`subjects_subjectId`)
    REFERENCES `gestorDatabase`.`subjects` (`subjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `gestorDatabase`.`students_has_parents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorDatabase`.`students_has_parents` (
  `students_studentId` INT NOT NULL,
  `parents_parentId` INT NOT NULL,
  PRIMARY KEY (`students_studentId`, `parents_parentId`),
  INDEX `fk_students_has_parents_parents1_idx` (`parents_parentId` ASC) VISIBLE,
  INDEX `fk_students_has_parents_students1_idx` (`students_studentId` ASC) VISIBLE,
  CONSTRAINT `fk_students_has_parents_students1`
    FOREIGN KEY (`students_studentId`)
    REFERENCES `gestorDatabase`.`students` (`studentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_parents_parents1`
    FOREIGN KEY (`parents_parentId`)
    REFERENCES `gestorDatabase`.`parents` (`parentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `gestorDatabase`.`teachers_has_subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorDatabase`.`teachers_has_subjects` (
  `teachers_teacherId` INT NOT NULL,
  `subjects_subjectId` INT NOT NULL,
  PRIMARY KEY (`teachers_teacherId`, `subjects_subjectId`),
  INDEX `fk_teachers_has_subjects_subjects1_idx` (`subjects_subjectId` ASC) VISIBLE,
  INDEX `fk_teachers_has_subjects_teachers1_idx` (`teachers_teacherId` ASC) VISIBLE,
  CONSTRAINT `fk_teachers_has_subjects_teachers1`
    FOREIGN KEY (`teachers_teacherId`)
    REFERENCES `gestorDatabase`.`teachers` (`teacherId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teachers_has_subjects_subjects1`
    FOREIGN KEY (`subjects_subjectId`)
    REFERENCES `gestorDatabase`.`subjects` (`subjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf32;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gestorDatabase`.`students`
-- -----------------------------------------------------
START TRANSACTION;
USE `gestorDatabase`;
INSERT INTO `gestorDatabase`.`students` ( `name`, `surname`, `email`, `password`) VALUES ( 'Ziutek', 'Zuzowski', 'ziutek@yyy.pl', 'ziutek123');
INSERT INTO `gestorDatabase`.`students` ( `name`, `surname`, `email`, `password`) VALUES ( 'Ziutka', 'Zenowska', 'ziutka@xxx.pl', 'ziutka123');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gestorDatabase`.`teachers`
-- -----------------------------------------------------
START TRANSACTION;
USE `gestorDatabase`;
INSERT INTO `gestorDatabase`.`teachers` ( `name`, `surname`, `email`, `password`) VALUES ( 'Adam', 'Adaski', 'adamadamski@xyz.pl', 'adamadamski123');
INSERT INTO `gestorDatabase`.`teachers` ( `name`, `surname`, `email`, `password`) VALUES ( 'Bartosz', 'Bartowski', 'bartoszbartowski@xxx.pl', 'bartoszbartowski123');
INSERT INTO `gestorDatabase`.`teachers` ( `name`, `surname`, `email`, `password`) VALUES ( 'Cecylian', 'Cecylowski', 'cecyliancecylowski@zz.pl', 'cecyliancecylowski123');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gestorDatabase`.`parents`
-- -----------------------------------------------------
START TRANSACTION;
USE `gestorDatabase`;
INSERT INTO `gestorDatabase`.`parents` ( `name`, `surname`, `email`, `password`) VALUES ( 'Zenon', 'Zenowski', 'zenonzenowski123@yy.pl', 'zenonzenowski123');
INSERT INTO `gestorDatabase`.`parents` ( `name`, `surname`, `email`, `password`) VALUES ( 'Zenna', 'Zuzowska', 'zennazuzowska123@xx.pl', 'zennazuzowska123');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gestorDatabase`.`subjects`
-- -----------------------------------------------------
START TRANSACTION;
USE `gestorDatabase`;
INSERT INTO `gestorDatabase`.`subjects` ( `name`) VALUES ( 'Logika');
INSERT INTO `gestorDatabase`.`subjects` ( `name`) VALUES ( 'Matematyka');
INSERT INTO `gestorDatabase`.`subjects` ( `name`) VALUES ( 'Ekonomia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gestorDatabase`.`grades`
-- -----------------------------------------------------
START TRANSACTION;
USE `gestorDatabase`;
INSERT INTO `gestorDatabase`.`grades` ( `value`, `students_studentId`, `subjects_subjectId`) VALUES ( 5, 1, 1);
INSERT INTO `gestorDatabase`.`grades` ( `value`, `students_studentId`, `subjects_subjectId`) VALUES ( 4, 2, 1);
INSERT INTO `gestorDatabase`.`grades` ( `value`, `students_studentId`, `subjects_subjectId`) VALUES ( 6, 1, 2);
INSERT INTO `gestorDatabase`.`grades` ( `value`, `students_studentId`, `subjects_subjectId`) VALUES ( 3, 2, 2);
INSERT INTO `gestorDatabase`.`grades` ( `value`, `students_studentId`, `subjects_subjectId`) VALUES ( 2, 1, 3);
INSERT INTO `gestorDatabase`.`grades` ( `value`, `students_studentId`, `subjects_subjectId`) VALUES ( 5, 2, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gestorDatabase`.`students_has_parents`
-- -----------------------------------------------------
START TRANSACTION;
USE `gestorDatabase`;
INSERT INTO `gestorDatabase`.`students_has_parents` (`students_studentId`, `parents_parentId`) VALUES (1, 1);
INSERT INTO `gestorDatabase`.`students_has_parents` (`students_studentId`, `parents_parentId`) VALUES (2, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gestorDatabase`.`teachers_has_subjects`
-- -----------------------------------------------------
START TRANSACTION;
USE `gestorDatabase`;
INSERT INTO `gestorDatabase`.`teachers_has_subjects` (`teachers_teacherId`, `subjects_subjectId`) VALUES (1, 1);
INSERT INTO `gestorDatabase`.`teachers_has_subjects` (`teachers_teacherId`, `subjects_subjectId`) VALUES (2, 2);
INSERT INTO `gestorDatabase`.`teachers_has_subjects` (`teachers_teacherId`, `subjects_subjectId`) VALUES (2, 3);

COMMIT;

